[package]
name = "cli_app"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.43"
anyhow= "1.0.98"
config="0.15.13"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
axum="0.8.4"
tokio = { version = "1.44", features = ["full"] }
arc-swap = "1.7.1"